;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	cua-paste
	end-of-visual-line
	indent-for-tab-command
	markdown-outdent-or-delete
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	avy-goto-char-timer
	cua--prefix-override-handler
	cua-copy-region
	))
